### ISSUE TITLE
Make tracking of amendments simpler

### ISSUE THREAD

**Issue by longhotsummer** [Code4SA/indigo#16]
It's currently complex to apply new amendments to an existing document. You need to ensure that the amending document is in the library, link to it, ensure you're editing the right one, etc.

Instead, treat a collection of expressions of a single work, and the linked amendments, as a logic model.

- [x] show amendments and amended versions together
- [x] make newly created doc FRBR URIs random
- [x] ensure adding/editing/removing amendments works
- [x] save all modified documents
- [x] limit the choices of expression date
- [x] keep unsaved amendments when creating a new expression (cloning doesn't include the at-date amendment)
- [x] migration to make docs with generic import URIs random

**Comment by longhotsummer** [comment]
Tracking some of this in the https://github.com/Code4SA/indigo/tree/expressions branch
